### ISSUE TITLE
not working nowadays

### ISSUE THREAD

**Issue by Nurlan199206** [sunfoxcz/ansible-dkim#1]
Hi.

you have tested your playbook in 2018?

**Comment by foxycode** [comment]
@Nurlan199206 Yes, I am still using it, but only for Ubuntu 16.04. What is the problem?

**Comment by Nurlan199206** [comment]
testing on ubuntu 18.04, trying to run dkim.yml

```
---
- hosts: myserver
  user: root
  sudo: False
  roles:
    - role: sunfoxcz.dkim
      dkim_selector: mail
      dkim_domains:
       - domain1.tld
       - domain2.tld
```

ansible-playbook /home/nurlan/ansible-dkim/dkim.yml
 [WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

[DEPRECATION WARNING]: Instead of sudo/sudo_user, use become/become_user and make sure become_method is 'sudo' (default). This feature will be removed in version 2.6. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.
ERROR! the role 'sunfoxcz.dkim' was not found in /home/nurlan/ansible-dkim/roles:/root/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles:/home/nurlanizimbetov/ansible-dkim

The error appears to have been in '/home/nurlan/ansible-dkim/dkim.yml': line 6, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

  roles:
    - role: sunfoxcz.dkim

**Comment by foxycode** [comment]
You have problem in your system.

1. Ansible can't find role. Put it for example to `/etc/ansible/roles` or update `roles_path` directive in `/etc/ansible/ansible.cfg` file.
2. First warning is related to hosts file, which you probably don't have or your host is missing there. See `inventory` directive in `/etc/ansible/ansible.cfg` file.
3. Second warning is because you are using deprecated `sudo` directive in you playbook (I know it's in my example :)

My `/etc/ansible/ansible.cfg`:
```ini
[defaults]
inventory     = ~/ansible/hosts
roles_path    = ~/ansible/roles:/etc/ansible/roles
```

My hosts file:
```ini
[ubuntu-18]
host1 ansible_host=host1.domain.tld

[ubuntu-18:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
```

My playbook:
```yml
- hosts: ubuntu-18
  remote_user: root # not needed when you have it in hosts file
  roles:
   - role: sunfoxcz.dkim
     dkim_selector: mail
     dkim_domains:
      - domain1.tld
      - domain2.tld
```

Let me know if it works.
